# Use Clang with Mold for fast linking on Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

# Use LLD for linking on macOS (Darwin)
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Use lld-link for fast linking on Windows (MSVC toolchain)
[target.x86_64-pc-windows-msvc]
linker = "lld-link"

